# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [16]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9118, 0.8472, 0.6201],
        [0.0446, 0.9455, 0.3200],
        [0.6793, 0.4955, 0.3660],
        [0.2731, 0.6481, 0.4719],
        [0.0447, 0.1662, 0.0464]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2 #setto da riga uno fino a riga 3 (esclusa) a 2
print(x)

tensor([[0.4590, 0.9146, 0.6581],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2271, 0.2309, 0.6095],
        [0.4739, 0.5602, 0.5657]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [10]:
tensor = torch.rand(2, 17)
float_tensor = torch.FloatTensor(3,1)
long_tensor = torch.LongTensor(5,2,1).fill_(7)

print(tensor)
print(float_tensor)
print(long_tensor)


tensor([[0.5016, 0.3253, 0.0843, 0.4363, 0.9960, 0.1676, 0.7805, 0.3192, 0.7227,
         0.7139, 0.7785, 0.8916, 0.4812, 0.7825, 0.5827, 0.6475, 0.0044],
        [0.1289, 0.4858, 0.5689, 0.1361, 0.0441, 0.0739, 0.8408, 0.2170, 0.6491,
         0.9613, 0.4769, 0.6164, 0.0055, 0.8377, 0.9391, 0.6844, 0.4531]])
tensor([[0.],
        [0.],
        [0.]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1430, 1.6081, 0.9318],
        [2.2803, 2.3577, 2.3878],
        [2.8035, 2.6448, 2.0352],
        [0.8276, 0.4613, 0.8136],
        [0.8892, 0.7823, 1.4739]])


### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[1.1430, 1.6081, 0.9318],
        [2.2803, 2.3577, 2.3878],
        [2.8035, 2.6448, 2.0352],
        [0.8276, 0.4613, 0.8136],
        [0.8892, 0.7823, 1.4739]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1430, 1.6081, 0.9318],
        [2.2803, 2.3577, 2.3878],
        [2.8035, 2.6448, 2.0352],
        [0.8276, 0.4613, 0.8136],
        [0.8892, 0.7823, 1.4739]])


### 2.4 Addition: in-place

adds `x`to `y`

In [14]:
y.add_(x)
print(y)

tensor([[1.1430, 1.6081, 0.9318],
        [2.2803, 2.3577, 2.3878],
        [2.8035, 2.6448, 2.0352],
        [0.8276, 0.4613, 0.8136],
        [0.8892, 0.7823, 1.4739]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [17]:
print(x[:, 1])

tensor([0.8472, 0.9455, 0.4955, 0.6481, 0.1662])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [18]:
import torch

# 1. Multiply two tensors
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])
result_mul = tensor_a.mul(tensor_b)
print("Multiplication result:", result_mul)

# 2. Multiply two tensors inplace
tensor_a.mul_(tensor_b)
print("Inplace multiplication result:", tensor_a)

# 3. Division of two tensors
tensor_c = torch.tensor([10, 20, 30, 40])
tensor_d = torch.tensor([2, 4, 5, 8])
result_div = tensor_c.div(tensor_d)
print("Division result:", result_div)

# 4. Perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)
tensor_e = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
tensor_f = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
result_matmul = torch.matmul(tensor_e, tensor_f)
print("Matrix multiplication result:\n", result_matmul)

Multiplication result: tensor([ 5, 12, 21, 32])
Inplace multiplication result: tensor([ 5, 12, 21, 32])
Division result: tensor([5., 5., 6., 5.])
Matrix multiplication result:
 tensor([[ 50,  60],
        [114, 140]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [23]:
tensor = torch.ones(5,2)
numpy_array = tensor.numpy()
tensor2 = torch.from_numpy(numpy_array)
print(tensor2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [28]:

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    print("MPS device is available.")
else:
    print("MPS device is not available.")
    
device = torch.device("mps") 
 
x = x.to("mps")
y = y.to(device)
z = x + y
# Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
# This is meant as a tensor to be run on the GPU.
# The .cuda() does this to any parameter it is applied to.
print(x)
print(y)
print(z)


MPS device is available.
tensor([[0.9118, 0.8472, 0.6201],
        [0.0446, 0.9455, 0.3200],
        [0.6793, 0.4955, 0.3660],
        [0.2731, 0.6481, 0.4719],
        [0.0447, 0.1662, 0.0464]], device='mps:0')
tensor([[1.1430, 1.6081, 0.9318],
        [2.2803, 2.3577, 2.3878],
        [2.8035, 2.6448, 2.0352],
        [0.8276, 0.4613, 0.8136],
        [0.8892, 0.7823, 1.4739]], device='mps:0')
tensor([[2.0548, 2.4553, 1.5519],
        [2.3249, 3.3032, 2.7078],
        [3.4828, 3.1403, 2.4012],
        [1.1007, 1.1094, 1.2854],
        [0.9339, 0.9485, 1.5203]], device='mps:0')


In [24]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
